### ISSUE TITLE
Add ARKX

### ISSUE THREAD

**Issue by MichaelDeBoey** [tigger0jk/ark-invest-scraper#3]
https://ark-funds.com/arkx

**Comment by tigger0jk** [comment]
Hmmm, they link to the pdf https://ark-funds.com/wp-content/fundsiteliterature/holdings/ARK_SPACE_EXPLORATION_&_INNOVATION_ETF_ARKX_HOLDINGS.pdf but not the csv yet, but I'm predicting the URL will follow their pattern though and be https://ark-funds.com/wp-content/fundsiteliterature/csv/ARK_SPACE_EXPLORATION_&_INNOVATION_ETF_ARKX_HOLDINGS.csv which doesn't resolve yet. I'm going to wait for that to resolve before adding that to the scraper so I don't scrape a 404. I think the fund goes live tomorrow so presumably they will upload the csv after it's truly live?

**Comment by MichaelDeBoey** [comment]
@tigger0jk Both the PDF & CSV are available right now

**Comment by tigger0jk** [comment]
Thanks - it's in! https://github.com/tigger0jk/ark-invest-scraper/commit/2393068def8d75f948b756ebefd20d84e944e062#diff-69f1375e08b67f2ca90b014881cd6ced72f44f8048a70b6a269c77f3e1e924a9

**Comment by MichaelDeBoey** [comment]
Nice, thanks! 👊🎉
