### ISSUE TITLE
Update `User-Agent` header

### ISSUE THREAD

**Issue by MichaelDeBoey** [tigger0jk/ark-invest-scraper#5]
It's there again (just like #2 & #4) 😢

**Comment by tigger0jk** [comment]
Sorry I'm slow to respond here - is it busted? Latest commits seem fine and even back when this was logged around 5/1 it seems fine to me? Don't think it even missed a day although it can miss one if they upload later than usual to the website. Let me know.

**Comment by MichaelDeBoey** [comment]
@tigger0jk It seems that only visiting https://ark-funds.com/investor-resources was causing issues
