### ISSUE TITLE
Error 404: ARK has changed their site 

### ISSUE THREAD

**Issue by rawmean** [tigger0jk/ark-invest-scraper#6]
Seems like ARK has changed their site and the static URL to the CSV files do not exist anymore

**Comment by tigger0jk** [comment]
Thanks for the report - it seems like they do still have them just at a different URL (viewable on website at https://ark-funds.com/funds/arkk/ for instance under the "holdings" section).

I've updated the script to pull from the new locations and removed the old files (https://github.com/tigger0jk/ark-invest-scraper/commit/1d5eb681ac8f3d1edcc3a650be1d3333c2a88c5f). The name of all of the files except `ARK_INNOVATION_ETF_ARKK_HOLDINGS.csv` have changed as you can see in this commit: https://github.com/tigger0jk/ark-invest-scraper/commit/6c5da7920f8235ef425abe6f8c3eca4fd01c5238 So some history tracking is lost/changed as of this breaking last week without a clever rename-tracking. If anyone is downstream and expecting specific filenames they will need to update them.
