### ISSUE TITLE
Add support for `CTRU`

### ISSUE THREAD

**Issue by MichaelDeBoey** [tigger0jk/ark-invest-scraper#7]
https://ark-funds.com/funds/ctru

**Comment by tigger0jk** [comment]
Thanks for the heads up - I will expect this to be in the same format as the other funds. So https://ark-funds.com/wp-content/uploads/funds-etf-csv/ARK_INNOVATION_ETF_CTRU_HOLDINGS.csv after the fund goes live, but that URL isn't active yet. Very easy change to make to scrape it, but I'm going to delay doing so until it's live so I don't scrape their 404 page.

According to the site, it goes live at 5PM EST on Wednesday December 8th. I will check back after that and try to make sure I update in time to catch the first scrape.

**Comment by MichaelDeBoey** [comment]
@tigger0jk 
- https://ark-funds.com/wp-content/uploads/funds-etf-pdf/ARK_TRANSPARENCY_ETF_CTRU_HOLDINGS.pdf
- https://ark-funds.com/wp-content/uploads/funds-etf-csv/ARK_TRANSPARENCY_ETF_CTRU_HOLDINGS.csv

**Comment by tigger0jk** [comment]
Awesome.
Scrape changes: https://github.com/tigger0jk/ark-invest-scraper/commit/1bd99d1cf3431bec6f47069029fc796cd8d2ec7c
First pull: https://github.com/tigger0jk/ark-invest-scraper/commit/8ce9ff804e2090ea65431817ac9a2205b3a14176
