### ISSUE TITLE
Only `ARKK` is updating since November 3rd

### ISSUE THREAD

**Issue by MichaelDeBoey** [tigger0jk/ark-invest-scraper#8]
Seems like only `ARKK` is updated since November 3rd (see https://github.com/tigger0jk/ark-invest-scraper/commit/23df374d9523207a8260921304701d6e824d61ef)

October 28th and before seems to be fine (see https://github.com/tigger0jk/ark-invest-scraper/commit/40afe8278cfcccef0836b42848a04e293ad0776e)

**Comment by tigger0jk** [comment]
Good catch.

They changed the filenames again (undoing https://github.com/tigger0jk/ark-invest-scraper/issues/6 I believe). Fix is in https://github.com/tigger0jk/ark-invest-scraper/commit/e36474aa87b79c90cdc3b72f3c3595266aa57bf5 for scraping adjustments and the new files.
